=== amanbisht9/blog_website_wsd_2047208/EmployeeInfoXmlSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
<xs:element name="Company">
  <xs:complexType>
      
    <xs:sequence>
      <xs:element name="Employee" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="EId" type="xs:integer"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="age" type="xs:integer"/>
            <xs:element name="salary" type="xs:integer" minExclusive="49000" maxExclusive="200001" />
            <xs:element name="emailid" type="xs:string"/>
            <xs:element name="phoneno" type="xs:integer"/>
            <xs:element name="designation" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    
  </xs:complexType> 
</xs:element>       

</xs:schema>

=== amanbisht9/blog_website_wsd_2047208/EmployeeInfoXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Employees.xsl" type="text/xsl"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="EmployeeInfoXmlSchema.xsd">
    <Employee>
        <EId>111</EId>
        <name>Drew Barrymore</name>
        <age>60</age>
        <salary>200000</salary>
        <emailid>allFriends23@gmail.com</emailid>
        <phoneno>557525125</phoneno>
        <designation>Associate Project Manager</designation>
    </Employee>
    
    <Employee>
        <EId>112</EId>
        <name>Derry Jackson</name>
        <age>59</age>
        <salary>100000</salary>
        <emailid>merryDerry911@gmail.com</emailid>
        <phoneno>94889542</phoneno>
        <designation>Associate Project Manager</designation>
    </Employee>

    <Employee>
        <EId>113</EId>
        <name>Ravi Shastri</name>
        <age>51</age>
        <salary>70000</salary>
        <emailid>ravishastri67@gmail.com</emailid>
        <phoneno>98745612</phoneno>
        <designation>Associate Project Manager</designation>
    </Employee>
    <Employee>
        <EId>114</EId>
        <name>Anubha Jauhari</name>
        <age>49</age>
        <salary>52000</salary>
        <emailid>anubhaJ7@gmail.com</emailid>
        <phoneno>98752621</phoneno>
        <designation>Team Leader</designation>
    </Employee>
    <Employee>
        <EId>115</EId>
        <name>Ratul Khalnayak</name>
        <age>31</age>
        <salary>50000</salary>
        <emailid>ratulKH123@gmail.com</emailid>
        <phoneno>98789855</phoneno>
        <designation>Developer</designation>
    </Employee>
    
</Company>
